[project]
name = "wsl-stats"
version = "0.1.0"
description = "A collection of WSL stats for fantasy football"
requires-python = ">=3.9"
dependencies = [
    "requests==2.32.5",
    "schedule==1.2.2",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
